import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './providers'
import Header from '@/components/header'
import { auth } from '@/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();

  return (
    <html lang="en" className="bg-stone-100">
      <body className={inter.className}>
        <div className='container mx-auto px-4 max-w-6xl'>
          <Providers>
            {(!session || !session.user) && <Header />}
            {children}
          </Providers>
        </div>
      </body>
    </html>
  )
}
